### ISSUE TITLE
Partial success response on the browser

### ISSUE THREAD

**Issue by devvader1** [SigNoz/sample-reactjs-app#3]
First off, thanks for putting up the tutorial. I've followed the steps laid out, but I am getting a partial success response for browser based/sample-reacjs-app traces, and the `link-frontend` service does not show up in the SigNoz UI.

I have another nodejs app (`node_app`) that exports to the same 4318 endpoint, and the `node_app` service shows up in the SigNoz UI.

My OTEL collector config is as below:

```
otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - http://localhost:3000  # URL of your Frontend application
            - http://localhost:1234  # URL of your Frontend application
        endpoint: 0.0.0.0:4318
```

The react app code is from this repository and the SigNoz backend is using the latest version (pull request #2225).

Guidance on this issue/likely gotchas' will be much appreciated.
